# Generated by Django 3.2 on 2022-10-16 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_defined_posts_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='saved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', related_query_name='bookmark', to='posts.question'),
        ),
    ]
