# Generated by Django 3.2 on 2022-02-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_added_null_to_Question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='posts.question'),
            preserve_default=False,
        ),
    ]
