# Generated by Django 3.2 on 2022-02-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_added_score_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='Answer',
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='Bookmark',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='questionpagehit',
            table='QuestionPageHit',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='Vote',
        ),
    ]
