# Generated by Django 3.2 on 2022-02-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_added_views_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'ordering': ['-score', '-date']},
        ),
        migrations.AlterModelOptions(
            name='questionpagehit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=75, unique_for_date='date'),
        ),
    ]
