# Generated by Django 3.2 on 2022-02-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_added_views_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=75, unique_for_date='date'),
        ),
    ]
