# Generated by Django 3.2 on 2022-03-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_created_unique_for_date_on_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(error_messages={'max_length': 'The title of your question is too long'}, help_text="Concisely state the problem you're having", max_length=55, unique_for_date='date'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('title', 'date', 'profile'), name='duplicated_post_by_date'),
        ),
    ]
