# Generated by Django 3.2 on 2022-03-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_added_unique_constraint_to_Question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(error_messages={'max_length': 'The title of your question is too long'}, help_text="Concisely state the problem you're having", max_length=80, unique_for_date='date'),
        ),
    ]
