# Generated by Django 3.2 on 2022-06-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_create_project_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can vote', 'Can vote')]},
        ),
    ]
